
:host = http://localhost:9000

# getHat
GET :host/api/secretsanta/0
GET :host/api/secretsanta/1
GET :host/api/secretsanta/20
GET :host/api/secretsanta/-5

# putHat
PUT :host/api/secretsanta
Content-Type: application/json;charset=utf-8
{ "owner" :
  { "name" : "brecht"
  , "email" : "services+secretsanta@brechtserckx.be"
  }
, "participants" :
  [ { "name" : "brecht1"
    , "email" : "services+secretsanta1@brechtserckx.be"
    }
  , { "name" : "brecht2"
    , "email" : "services+secretsanta2@brechtserckx.be"
    }
  , { "name" : "brecht3"
    , "email" : "services+secretsanta3@brechtserckx.be"
    }
  ]
}

# match
GET :host/api/secretsanta/0/match